version: "3"
services:
  postgres:
    build: postgres/
    ports:
      - 5432:5432
  web:
    build: web/
    volumes:
        - ./web/templates:/templates
    network_mode: host
    depends_on:
      - postgres
